trigger:
- master
- development

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DownloadBuildArtifacts@0
  displayName: 'Download CLI'
  inputs:
    buildType: 'specific'
    project: '7672f4c6-33ca-42f2-bfd8-1f88e64fbda5'
    pipeline: '1'
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/development'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(Build.SourcesDirectory)'

- task: ExtractFiles@1
  displayName: 'Extract CLI'
  inputs:
    archiveFilePatterns: '$(Build.SourcesDirectory)*.zip'
    destinationFolder: '$(Build.SourcesDirectory)'
    cleanDestinationFolder: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: CmdLine@2
  displayName: 'Remove postbuilds'
  inputs:
    script: 'sed -i ''/PostBuild/g'' Slipe/Core/Source/SlipeClient/SlipeClient.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build client'
  inputs:
    command: 'build'
    workingDirectory: 'Slipe/Core/Source/SlipeClient'

- task: CmdLine@2
  displayName: 'Remove postbuilds'
  inputs:
    script: 'sed -i ''/PostBuild/g'' Slipe/Core/Source/SlipeClient/SlipeServer.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build server'
  inputs:
    command: 'build'
    workingDirectory: 'Slipe/Core/Source/SlipeServer'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.sln'
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'